spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/earthQuakeDB
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update